#Discord
TROUBLESHOOT_WEBHOOK_URL: "DISCORD WEBHOOK URL"
WARN_LOG_WEBHOOK_URL: "DISCORD WEBHOOK URL"
DISCORD_BOT_TOKEN: "BOT TOKEN"
DISCORD_MOD_ROLE_ID: "MOD ROLE ID"
DISCORD_ADMIN_ROLE_ID: "ADMIN ROLE ID"

#Warn Reasons -- See e.g. below
WARN_REASONS:
  - 1 Spam
  - 2a Idk
  - 2b Cba
  - 3 Tldr