name: MinecraftEasyWarnings
version: '1.0'
main: mplugin.net.minecraftEasyWarnings.MinecraftEasyWarnings
api-version: '1.21'
authors: [ Dillsteamgamer ]

commands:
    warn:
      description: Issue a warning to a player
      permission: warnings.moderator
      default: op
      usage: /warn <Player> <Reason>
    warnings:
      description: Check the warnings a player has
      permission: warnings.moderator
      default: op
      usage: /warnings <Player>
    deleteWarning:
      description: Delete a warning by its ID
      permission: warnings.admin
      default: op
      usage: /deleteWarning <Id>